### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by manuelmelle** [ccdc-opensource/dash#17]
Hi, 

Very nice idea to make DASH open source. However, all compilation instructions are for in windows and our compilation setup is for Linux. Are you planning to provide binaries for windows, or, even better to provide a compilation mechanism for Linux machines?

regards

Manuel

**Comment by rockdreamer** [comment]
Hi @manuelmelle , we provide binaries in the releases section. Here's the [3.99.2](https://github.com/ccdc-opensource/dash/releases/tag/3.99.2) ones.

Due to licensing restrictions with Winteracter and infrastructure security considerations, we can't provide builds of pull requests.
The build mechanism itself can support compilation on Linux but the codebase is not compatible with gfortran. We would welcome contributions in that direction.

**Comment by rockdreamer** [comment]
Hi @manuelmelle , I've added instructions on [setting up a Linux build machine](https://github.com/ccdc-opensource/dash/wiki/Provisioning-a-build-machine) and [Building DASH](https://github.com/ccdc-opensource/dash/wiki/Building-DASH)

The xmas_updates branch should already be workable but needs a reviewer.

**Comment by rockdreamer** [comment]
Hi @manuelmelle , we released a linux binary with version 4.0.0. Cheers! :)

**Comment by mspillman** [comment]
@manuelmelle I have had success in the past running DASH on Linux using wine, so if the build process doesn't work, that might make for a reasonable workaround.
